# Generated by Django 5.1.6 on 2025-02-25 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(choices=[('norte', 'Norte'), ('taguatinga', 'Taguatinga'), ('ambos', 'Ambos')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='adesao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campus'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together={('professor', 'dia_da_semana', 'campus')},
        ),
    ]
