# Generated by Django 5.1.6 on 2025-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_campus_adesao_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adesao',
            name='observacao',
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField(unique=True)),
                ('turmas', models.ManyToManyField(blank=True, to='app.turma')),
            ],
        ),
    ]
