# Generated by Django 5.1.6 on 2025-04-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_adesao_observacao_disponibilidade_observacao_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turma',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campus'),
        ),
        migrations.AddField(
            model_name='turma',
            name='tag',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('professor', 'materia', 'dia_da_semana', 'campus')},
        ),
    ]
