# Generated by Django 5.1.6 on 2025-04-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_turma_unique_together_turma_campus_turma_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
    ]
