# Generated by Django 5.1.6 on 2025-05-04 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_turma_status_alter_turma_professor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('professor', 'materia', 'campus')},
        ),
        migrations.AlterField(
            model_name='turma',
            name='dia_da_semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.diasdasemana'),
        ),
    ]
