# Generated by Django 5.1.6 on 2025-06-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_turma_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.campus'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='dias_da_semana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.diasdasemana'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
