# Generated by Django 5.1.6 on 2025-06-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_semestre_campus_semestre_dias_da_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campus'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='dias_da_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diasdasemana'),
        ),
    ]
