# Generated by Django 5.1.6 on 2025-06-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_semestre_campus_alter_semestre_dias_da_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='dias_da_semana',
        ),
        migrations.AddField(
            model_name='semestre',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=5),
        ),
    ]
