# Generated by Django 5.1.6 on 2025-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_semestre_dias_da_semana_semestre_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='tag',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
