# Generated by Django 5.1.6 on 2025-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_semestre_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='tag',
            field=models.CharField(max_length=3),
        ),
    ]
